#!/usr/bin/env bash

# The purpose of this custom AppRun script is to allow symlinking the AppImage
# and invoking the corresponding binary depending on which symlink was used
# to invoke the AppImage

HERE="$(dirname "$(readlink -f "${0}")")"

source "$HERE"/apprun-hooks/"linuxdeploy-plugin-gtk.sh"

if [[ ! -z $APPIMAGE ]] ; then
  BINARY_NAME=$(basename "$ARGV0")
  if [[ ! -z "$1" ]] && [[ -e "$HERE/usr/bin/$1" ]] ; then
    EXECFILE="$HERE/usr/bin/$1" ; shift
  elif [[ -e "$HERE/usr/bin/$BINARY_NAME" ]] ; then
    EXECFILE="$HERE/usr/bin/$BINARY_NAME"
  else
    EXECFILE="$HERE/usr/bin/darktable"
  fi
else
  EXECFILE="$HERE/usr/bin/darktable"
fi

exec "$EXECFILE" "$@"
