#!/usr/bin/python3

# Requires:
#   python3-opencv
#   python3-numpy
#   python3-colour (recent version needed, see below):
#      pip3 install colour-science

# Maximum delta allowed, above this value the difference can be detected
MAX_DELTA_E = 2.3
MAX_AVG_DELTA_E = MAX_DELTA_E / 3.

import cv2
import colour
import numpy
import os
import sys

if "delta_E" not in dir(colour):
    print("  Unable to compute delta-E, please upgrade python3-colour-science")
    exit(0)

expected = sys.argv[1]
output = sys.argv[2]

expected_rgb = cv2.imread(expected)
output_rgb = cv2.imread(output)

expected_lab = cv2.cvtColor(expected_rgb, cv2.COLOR_RGB2Lab)
output_lab = cv2.cvtColor(output_rgb, cv2.COLOR_RGB2Lab)

delta_E = colour.delta_E(expected_lab, output_lab, method="CIE 2000")

num_elem = delta_E.size

max_dE = numpy.amax(delta_E)
mean_dE = numpy.mean(delta_E)
std_dE = numpy.std(delta_E)

print("      ----------------------------------")
print("      Max dE                   : %.5f" % max_dE)
print("      Avg dE                   : %.5f" % mean_dE)
print("      Std dE                   : %.5f" % std_dE)
print("      ----------------------------------")

count_below_avg = numpy.sum(delta_E <= mean_dE)
print("      Pixels below avg + 0 std : %.2f %%" % (count_below_avg / num_elem * 100.))

count_below_avg = numpy.sum(delta_E <= mean_dE + std_dE)
print("      Pixels below avg + 1 std : %.2f %%" % (count_below_avg / num_elem * 100.))

count_below_avg = numpy.sum(delta_E <= mean_dE + 3. * std_dE)
print("      Pixels below avg + 3 std : %.2f %%" % (count_below_avg / num_elem * 100.))

count_below_avg = numpy.sum(delta_E <= mean_dE + 6. * std_dE)
print("      Pixels below avg + 6 std : %.2f %%" % (count_below_avg / num_elem * 100.))

count_below_avg = numpy.sum(delta_E <= mean_dE + 9. * std_dE)
print("      Pixels below avg + 9 std : %.2f %%" % (count_below_avg / num_elem * 100.))

print("      ----------------------------------")

count_above = numpy.sum(delta_E >= MAX_DELTA_E)
print("      Pixels above tolerance   : %.2f %%" % (count_above / num_elem * 100.))

if(max_dE > MAX_DELTA_E or mean_dE > MAX_AVG_DELTA_E):
    exit(2)
elif(max_dE < 0.01):
    exit(0)
else:
    exit(1)
