#!/usr/bin/python3

# Requires:
#   python3-opencv
#   python3-numpy
#   python3-colour (recent version needed, see below):
#      pip3 install colour-science

# Maximum delta allowed, above this value the difference can be detected
MAX_DELTA_E = 2.0

import cv2
import colour
import numpy
import os
import sys

expected = sys.argv[1]
output = sys.argv[2]

image1_rgb = cv2.imread(expected)
image2_rgb = cv2.imread(output)

image1_lab = cv2.cvtColor(image1_rgb, cv2.COLOR_RGB2Lab)
image2_lab = cv2.cvtColor(image2_rgb, cv2.COLOR_RGB2Lab)

delta_E = colour.delta_E(image1_lab, image2_lab)

max_dE = numpy.max(delta_E)
mean_dE = numpy.mean(delta_E)
count_above = 0

print("      Max  dE         %.4f" % max_dE)

if(max_dE > MAX_DELTA_E):
    count_above = numpy.sum(delta_E >= MAX_DELTA_E)
    print("      Mean dE         %.4f" % mean_dE)
    print("      Count above max %d" % count_above)
    exit(1)

exit(0)
