#!/bin/sh
# See: http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=19805

orig_image=$1
jpeg_image=$2

exit 0

over=$(convert "$jpeg_image" -channel RGB -threshold 99% -separate -append -format "%[mean]" info: | cut -f1 -d.)
if [ "$over" -a "$over" -lt 80 ]; then
	# Image not over-exposed.
	echo "\"$orig_image\" not over-exposed ($over)"
	exit 1
fi

under=$(convert "$jpeg_image" -negate -channel RGB -threshold 99% -separate -append -format "%[mean]" info: | cut -f1 -d.)
if [ "$under" -a "$under" -lt 80 ]; then
	# Image not under-exposed.
	echo "\"$orig_image\" not under-exposed ($under)"
	exit 2
fi
