#!/bin/sh 

_raw=""
_keep=0
_quiet=0

while [ $# -gt 0 ] ; do
	case $1 in
	-k)
		_keep=1
		;;
	-q)
		_quiet=1
		;;
	*)
		_raw="$1"
		;;
	esac
	shift
done

_base=$(printf "$_raw"| sed s,'\(.*\)\..*$','\1',g)
TMPPPM="${_base}.ppm"
TMPJPG="${_base}.jpg"
PPM16="${_base}-16.ppm"
PPM8="${_base}-8.ppm"

# convert RAW to linear 16bit PPM
dcraw -6 -W -g 1 1 -w "$_raw"
mv "$TMPPPM" "$PPM16"

# Extract embedded JPEG file from RAW for known brands
_make=$(exiftool -Make -t "$_raw"|cut -d "$(printf '\t')" -f 2)
case "$_make" in
[Nn][Ii][Kk][Oo][Nn]*)
	exiftool -b -JpgFromRaw "$_raw" > "$TMPJPG"
	;;
[Cc][Aa][Nn][Oo][Nn]*)
	exiftool -b -PreviewImage "$_raw" > "$TMPJPG"
	;;
*)
	echo "unknown camera manufacturer $_make, please inform darktable developers"
	exit 1
	;;
esac

# deal with the orientation flag
_orientation=$(exiftool -t -n -Orientation "$_raw"|cut -d "$(printf '\t')" -f 2)
case "$_orientation" in
 1) transform="";;
 2) transform="-flip horizontal";;
 3) transform="-rotate 180";;
 4) transform="-flip vertical";;
 5) transform="-transpose";;
 6) transform="-rotate 90";;
 7) transform="-transverse";;
 8) transform="-rotate 270";;
 *) transform="";;
esac

# convert from JPEG to PPM
convert $transform "$TMPJPG" "$PPM8"
rm -f "$TMPJPG"

# analyze the image w/ the tool
dt-curve-tool "$PPM16" "$PPM8"
if [ $_keep -eq 0 ] ; then
	rm "$PPM16" "$PPM8"
fi

if [ "$_quiet" -eq 0 ] ; then
	echo "if you accumulated enough data, you can now output the curves with"
	echo "dt-curve-tool -z -e "$_raw" -n 16"
fi
