#!/usr/bin/env python3
"""Generate a raster-mask coverage harvest for `darktable --verify-masks`.

WHY THIS IS GENERATED RATHER THAN HARVESTED

The real-library harvest is what proves the migration works on edits people
actually made, and for raster masks it does: 123 of them, 118 with a mask that
genuinely varies, all identical after migration. But a corpus reflects how one
person works, and this one is thin exactly where a bug would hide -- the global
blur refinement appears in 1 of the 123 edits, and inversion never co-occurs
with a details threshold at all.

Classic raster masks are a small, closed space: raster mode is exclusive (it
cannot be combined with a drawn or parametric mask), so an edit is fully
described by its source, an invert flag, the module opacity, and the global
refinements applied downstream. That is enumerable, so it is enumerated here
instead of being sampled and hoped over.

The output is an ordinary harvest file -- same schema --verify-masks already
reads -- so it needs no new machinery, contains no user data, and can be
shared or regenerated by anyone:

    ./gen_raster_matrix.py raster_matrix.json
    darktable --verify-masks raster_matrix.json

WHAT IT DOES NOT COVER

The raster mask handed to the module is synthesised by the verifier, not
replayed from a real upstream module, and the fetch itself (dt_dev_get_raster_
mask) is shared code that both sides call identically -- so this exercises the
composition and refinement of a raster mask, not the pipe's raster plumbing.
"""

import json
import sys

# Lab (2) and scene-referred RGB (4) take different paths through the blendif
# code, and the feathering guide weight/epsilon differ by colour space, so both
# are worth crossing rather than picking one.
COLOURSPACES = [(2, "Lab", "exposure"), (4, "rgb_scene", "colorbalancergb")]

INVERT = [0, 1]
OPACITY = [100.0, 45.0]
FEATHER = [0.0, 25.0]
BLUR = [0.0, 12.0]
# brightness and contrast share one post-processing step (the mask tone curve),
# so they are one axis with three states rather than two independent ones
TONE = [(0.0, 0.0), (0.35, 0.0), (0.0, 0.35)]
# details is signed: the sign selects which side of the detail threshold is
# kept, so both directions have to appear
DETAILS = [0.0, 0.30, -0.30]


def make_edit(index, cst, cst_name, op, invert, opacity, feather, blur, tone, details):
    brightness, contrast = tone
    return {
        "index": index,
        "image_index": 0,
        # a non-square image: mask geometry is stored normalised, so a square
        # probe would hide an aspect-ratio error
        "image": {"width": 3000, "height": 2000},
        "operation": op,
        "multi_priority": 0,
        "enabled": 1,
        # the version every classic raster edit is read back as
        "blendop_version": 14,
        "blend": {
            # DEVELOP_MASK_ENABLED | DEVELOP_MASK_RASTER
            "mask_mode": 1 | 8,
            "blend_cst": cst,
            "blend_cst_name": cst_name,
            "blend_mode": 0,
            "blend_parameter": 0.0,
            "opacity": opacity,
            "mask_combine": 0,
            "mask_id": 0,
            "blendif": 0,
            "feathering_radius": feather,
            # 5 == guide by the module's output; the input-side guide is
            # covered by the harvested corpus
            "feathering_guide": 5,
            "blur_radius": blur,
            "contrast": contrast,
            "brightness": brightness,
            "details": details,
            "feather_version": 1,
            "blendif_parameters": [0.0] * 64,
            "blendif_boost_factors": [0.0] * 16,
            # the verifier stands up a stand-in source module under this name;
            # instance 0 / id 0 is what every real raster edit uses
            "raster_mask_source": "exposure",
            "raster_mask_instance": 0,
            "raster_mask_id": 0,
            "raster_mask_invert": invert,
        },
        "forms": [],
    }


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "raster_matrix.json"

    edits = []
    for cst, cst_name, op in COLOURSPACES:
        for invert in INVERT:
            for opacity in OPACITY:
                for feather in FEATHER:
                    for blur in BLUR:
                        for tone in TONE:
                            for details in DETAILS:
                                edits.append(
                                    make_edit(
                                        len(edits), cst, cst_name, op, invert,
                                        opacity, feather, blur, tone, details,
                                    )
                                )

    doc = {
        "format": "darktable mask harvest",
        "format_version": 1,
        "darktable_version": "generated",
        "current_blend_version": 15,
        "current_masks_version": 7,
        "contents": "generated raster-mask coverage matrix; contains no user data",
        "edits": edits,
        "summary": {"images": 1, "edits": len(edits)},
    }

    with open(out, "w") as f:
        json.dump(doc, f, indent=1)
    print(f"wrote {len(edits)} generated raster edits to {out}")


if __name__ == "__main__":
    main()
