Document: darktable
Title: Debian darktable Manual
Author: <insert document author here>
Abstract: This manual describes what darktable is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/darktable/darktable.sgml.gz

Format: postscript
Files: /usr/share/doc/darktable/darktable.ps.gz

Format: text
Files: /usr/share/doc/darktable/darktable.text.gz

Format: HTML
Index: /usr/share/doc/darktable/html/index.html
Files: /usr/share/doc/darktable/html/*.html
