#!/usr/bin/env ruby

if ARGV.size != 2
  $stderr.puts "Usage: compare <from branch> <to branch>"
  exit 2
end

# Limit of number of files to process per camera, nil is unlimited
PER_CAMERA_LIMIT=nil

require File.expand_path "src/all.rb", File.dirname(__FILE__)

# Lets setup our environment first
build_c_util("imgcmp")
from = DTBuild.new ARGV[0]
to = DTBuild.new ARGV[1]
fetch_samples
runner = Runner.new(:camera_limit => PER_CAMERA_LIMIT)

runner.compare_web(from, to, "comparison")
